FROM bluenviron/mediamtx:latest

# Copia configuracao customizada
COPY mediamtx.yml /mediamtx.yml

# Portas expostas
EXPOSE 8554/tcp
EXPOSE 8554/udp
EXPOSE 8889/tcp
EXPOSE 8889/udp
EXPOSE 8888/tcp
EXPOSE 9997/tcp
EXPOSE 1935/tcp
